title: Monlam AI
logo: /assets/img/Monlam AI logo.jpg
description: Artificial intelligence in service of Tibetan language and culture
show_downloads: False
theme: jekyll-theme-minimal
navigation:
  - title: Home
    url: /
  - title: Monlam Translate
    url: /translation
  - title: Monlam OCR
    url: /ocr
  - title: Monlam Speech
    url: /stt
  - title: Partners
    url: /partners
  - jobs: Job Application
    url: /job
