title: Monlam AI
logo: /assets/img/logo.png
description: AI in the service of Tibetan language and culture
show_downloads: False
theme: jekyll-theme-minimal
navigation:
  - title: Home
    url: /
  - title: Partners
    url: /partners
